version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
  bats: circleci/bats@1.0

jobs:
  commitlint:
    description: "This job uses CommitLint CLI to validate commits messages, starting from the latest tag."
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install and setup CommitLint CLI"
          command: |
            npm install --quiet --no-progress @commitlint/cli@16 @commitlint/config-conventional@16
      - run:
          name: "Validate commits messages, starting from the latest tag."
          command: |
            npx commitlint --from $(git describe --tags --abbrev=0) --to HEAD --verbose

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - commitlint:
          filters: *filters
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters: *filters
      - bats/run:
          path: ./src/scripts/**
          filters: *filters
      - orb-tools/publish:
          orb-name: gravitee-io/keeper
          vcs-type: << pipeline.project.type >>
          requires:
            - commitlint
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
            - bats/run
          # Use a context to hold your publishing token.
          context: keeper-orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
